services:

  web:
    build: .
    container_name: bookflow-web

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    environment:
      - DB_HOST=db
      - DB_NAME=bookflow
      - DB_USER=root
      - DB_PASS=root

  db:
    image: mysql:8

    container_name: bookflow-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookflow

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    container_name: bookflow-phpmyadmin

    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "8081:80"

    depends_on:
      - db

volumes:
  db_data: